FLAGS = -Wall -std=c++14

all: a b c d

a: a.cpp
	g++ ${FLAGS} -o a a.cpp

b: b.cpp
	g++ ${FLAGS} -o b b.cpp

c: c.cpp
	g++ ${FLAGS} -o c c.cpp

d: d.cpp
	g++ ${FLAGS} -o d d.cpp

clean:
	rm -f a b c d
