FLAGES = -Wall -std=c++11

all: a b c d

a: polycarp_pocket.cpp
	g++ ${FLAGS} -o a polycarp_pocket.cpp

b: coins_and_triangle.cpp
	g++ ${FLAGS} -o b coins_and_triangle.cpp

c: elevator_trouble.cpp
	g++ ${FLAGS} -o c elevator_trouble.cpp

d: boat_burglary.cpp
	g++ ${FLAGS} -o d boat_burglary.cpp

clear:
	rm -f a b c d